# Generated by Django 3.1.3 on 2020-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_pic', models.ImageField(blank=True, null=True, upload_to='media/portfolio')),
                ('category', models.CharField(max_length=255)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
